# variables to configure the workflow on a global scale
basecall_fq: 
database_dir: 
demultiplex_dir:

threads:
  normal: 2 # common jobs
  large: 6 # threads-dependent jobs
mem:
  normal: 10
  large: 50
# runtime (h) only for cluster excution
runtime:
  default: 5
  long: 30
  simple: 1

##############################################################
# Demultiplex
demuxer: guppy # guppy | minibar 
guppy:
  barcode_kits: "SQK16S-GXO192"
minibar:
  args: "-p 0.75 -l 160"
nreads_m: 50 # rm barcoded samples in shallow sequencing
##############################################################
# Quality control
subsample: False
# filter reads by quality and length range
seqkit:
  n: 5000 # subsampling number [int]
  min_qual: 7
  min_len: 800
  max_len: 1500

# rm chimeras
rm_chimera: True
yacrd:
  c: 4
  n: 0.4

# trim primers
trim: True
# order matters
fprimer:
  27Fa: "AGAGTTTGATYMTGGCTYAG"
  27Fb: "AGGGTTCGATTCTGGCTCAG"
  338Fa: "ACWCCTACGGGWGGCAGCAG"
  338Fb: "GACTCCTACGGGAGGCWGCAG"
rprimer: 
  1540R: "TACGGYTACCTTGTTACGACT"
  1391R: "GACGGGCGGTGTGTRCA"

cutadapt:
  max_errors: 0.2
  min_overlap: 6

##############################################################
classifier: minimap2lca # emu|minimap2lca
minimap2lca:
  # megan lca params
  maxMatchesPerRead: 100
  topPercent: 10
  minSupportPercent: 0.01
  minPercentReadCover: 70
  minPercentReferenceCover: 0
  lcaAlgorithm: naive # naive|weighted|longReads 
  lcaCoveragePercent: 100

emu:
  # emu|rdp|silva|unite-fungi|unite-all
  prebuilt_database: emu